## YAML Template.
---
configuration : 
    - name : alice
      ip : 128.237.219.71
      port : 12345
    - name : bob
      ip : 128.237.219.71
      port : 12346
    - name : charlie
      ip : 128.237.219.71
      port : 12347
    - name : daphnie
      ip : 128.237.219.71
      port : 12348
    - name : ed
      ip : 128.237.219.71
      port : 12349
    - name : logger
      ip : 128.237.219.71
      port : 1988
    
sendRules : 
    - action : drop
      kind : impossiblekind
    
receiveRules :
    - action : drop
      kind : impossiblekind
